[tools]
erlang = "27.0"
elixir = "1.17.0"

[tasks.start]
description = "Start the server"
run = "mix phx.server"

[tasks.install]
description = "Install dependencies"
run = "mix deps.get"

[tasks.build_release]
description = "Build the release"
run = "mix release"

[tasks.migrate]
description = "DB migration"
run = "mix ecto.migrate"

[tasks.reset_db]
description = "reset the database"
run = "mix ecto.drop && mix ecto.create && mix ecto.migrate"

[tasks.build_image]
description = "build docker image"
# You can change elixir-chat to your desired image name
run = "docker build -t elixir-chat ."

[tasks.run_container]
description = "Run docker container"
# You can change elixir-chat to your desired image name
run = """
docker rm -f elixir-chat-container && \
docker run -itd --name elixir-chat-container \
  -p 4000:4000 \
  -v "$(pwd)/data:/data" \
  elixir-chat:latest
"""
