export const BACKEND_URL = "http://localhost:4000"
export const PROD_BACKEND_URL = "http://localhost:4000"
export const WS_URL = "ws://localhost:4000/socket/websocket"
export const PROD_WS_URL = "ws://localhost:4000/socket/websocket"
export const GH_PROJECT = "chat"
